# Reference - https://docs.docker.com/compose/compose-file/
version: '2.2'
services:
  web:
    image: aspendigital/octobercms:latest
    ports:
      - 80:80
    environment:
      - APP_DEBUG=true
      - CMS_ACTIVE_THEME=starter
      - CMS_BACKEND_SKIN=AspenDigital\Backend\Skins\Admin
      - INIT_PLUGINS=true
      - TZ=${TZ:-America/Denver}
    volumes:
      # A local `.env` is not required but expected if you wish to pass secrets to the config - see README.md
      # - ./.env:/var/www/html/.env

      - ./plugins:/var/www/html/plugins
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs

      # Uncomment the line below for a persistent local database - see README.md
      # - ./storage/database.sqlite:/var/www/html/storage/database.sqlite

      # Mounting the entire `themes` folder can cause performance issues in Docker for Mac
      # https://docs.docker.com/compose/compose-file/#caching-options-for-volume-mounts-docker-for-mac
      - ./themes:/var/www/html/themes
